Feature/tidy up legacy bits 2845223
FreelyGive/contacts pull request #11
Opened 2017-01-20 15:38 UTC by yanniboi

2017-01-23 17:01 UTC, yanniboi reviewed
Tests are passing @andrewbelcher what do you think?

2017-01-23 17:01 UTC, yanniboi commented on contacts.install
> +
This might be overkill now... What do you think?

2017-01-23 17:01 UTC, yanniboi commented on tests/src/Functional/ContactsDashboardTest.php
Help and block are dependencies of the theme.

2017-01-23 17:01 UTC, yanniboi commented on travis-ci/after/environments/drupal-8.sh
> +}
This is stopping the module being enabled for tests.

2017-01-23 17:10 UTC, andrewbelcher requested changes
Couple little changes needed and a few questions I think need answering...

2017-01-23 17:10 UTC, andrewbelcher commented on contacts.install
> +
I think we probably shouldn't do it as part of hook requirements... We could check that it is available for install, but do the actual install as part of `hook_install()`?

2017-01-23 17:10 UTC, andrewbelcher commented on contacts.install
> +        $requirements['theme'] = array(
`'theme'` is probably too non-specific - `$requirements` gets merged into an array with any other `hook_requirements()` returns, so should probably use `contacts_theme` or something?

2017-01-23 17:10 UTC, andrewbelcher commented on contacts.install
> +          'title' => t('Missing Theme'),
Can we be slightly more specific in the title? Something like 'Contacts theme missing'?

2017-01-23 17:10 UTC, andrewbelcher commented on tests/src/Functional/ContactsDashboardTest.php
This is missing documentation. An `@inheritdoc` with an additional comment as to why we're enabling those modules would be good.

On those requirements, are they hard requirements, or can we put them in as soft dependencies (i.e. wrap their use in checks)?

2017-01-23 17:10 UTC, andrewbelcher commented on tests/src/Functional/ContactsDashboardTest.php
>      \Drupal::service('theme_installer')->install(['contacts_theme']);
With it doing the install as part of `hook_requirements()` (or soon to be `hook_install()`), do we need to do it separately here? And, if not, can `contacts` just go in `self::$modules`?

2017-01-23 17:10 UTC, andrewbelcher commented on contacts.install
> +        $requirements['theme'] = array(
Need to check that it's not too late as part of `hook_install()` - not sure when the config dependencies are worked out...

2017-01-23 17:10 UTC, andrewbelcher commented on travis-ci/after/environments/drupal-8.sh
> +}
Nice :)

2017-01-23 17:30 UTC, yanniboi commented on contacts.install
> +
I wonder if hook_install is early enough but can look into that.

2017-01-23 17:32 UTC, yanniboi commented on tests/src/Functional/ContactsDashboardTest.php
Config. We add a help block to a region as part of the theme install. We might be able move the block to 'optional'?

2017-01-23 19:05 UTC, andrewbelcher commented on tests/src/Functional/ContactsDashboardTest.php
Yes, optional is the answer and then we can ditch them as dependencies at all!

2017-01-24 08:50 UTC, yanniboi commented
@andrewbelcher made changes and passing tests. Feel free to review/merge.

2017-01-24 09:09 UTC, andrewbelcher requested changes
Really good step forward, think we're very close!

2017-01-24 09:09 UTC, andrewbelcher commented on contacts.install
> +      $requirements['contacts_theme_missing'] = array(
Hmm... This is going to result in a requirements error if the theme is not installed, which means you now have to install it first. Can we check whether is is available to install before we mark an error?

2017-01-24 09:09 UTC, andrewbelcher commented on contacts.install
> +function contacts_module_preinstall() {
[`hook_module_preinstall($module)`](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_module_preinstall/8.2.x) is called on all installed modules whenever a module is installed, so we need to:

1) Check that this get's called (I'm pretty sure it is as it's added to the module list before the hook is invoked).
2) Add the argument and check that is is `contacts` being installed.
3) Does our test provide coverage for this process?

2017-01-24 09:09 UTC, andrewbelcher commented on contacts.install
> +      $requirements['contacts_theme_missing'] = array(
Think you need to use $theme_data = \Drupal::service('theme_handler')->rebuildThemeData() to see if a theme is available (see \Drupal\Core\Extension\ThemeInstaller::install).

2017-01-25 19:04 UTC, andrewbelcher commented
https://github.com/yanniboi/contacts/pull/11 resolves the remaining changes and adds a bit more test coverage

2017-01-26 10:03 UTC, merged