WIP: Added a default stacked layout for tab content.
FreelyGive/contacts pull request #64
Opened 2017-10-11 14:04 UTC by yanniboi

2017-10-11 14:04 UTC, yanniboi commented
This is going on top of #63

2017-10-17 09:21 UTC, andrewbelcher requested changes
Great direction. Definitely want to switch to core layout and move the layout and block rendering into a render element.

Also - couldn't comment directly on the image, but it's 2 col, but not stacked!

2017-10-17 09:21 UTC, andrewbelcher commented on contacts.module
> +  // @todo switch to core layout manager plugin.manager.core.layout?
Yes - definitely want to use the core layout module, including upping our core version requirement. No point implement the non core stuff...

2017-10-17 09:21 UTC, andrewbelcher commented on contacts.module
> +      $regions[$key] = $variables['content'][$key];
Mentioned in #63, but we should definitely move building the block render array into here and probably move it into a render element for OO bliss...

2017-10-17 09:21 UTC, andrewbelcher commented on contacts.module
> +  $variables['messages'] = $variables['content']['messages'];
What is done with `messages`?

2017-10-17 09:21 UTC, andrewbelcher commented on src/Controller/DashboardController.php
> +    $this->layoutManager = $layout_manager;
Moving to a render element should remove the need for this!

2017-10-17 09:21 UTC, andrewbelcher commented on src/Plugin/Block/ContactsDashboardTabs.php
> +    $this->layoutManager = $layout_manager;
Another duplication a render element will solve...

2017-10-17 09:21 UTC, andrewbelcher commented on templates/contacts-dash-tab-content.html.twig
> +  {{ content }}
Do we even need this now we've got layout handling it?

2017-10-20 14:53 UTC, andrewbelcher requested changes

2017-10-20 14:53 UTC, andrewbelcher commented on contacts.module
> +function template_preprocess_contacts_tab_content_stacked(array &$variables) {
Let's drop the pre-process, we can use `$content['region']['#prefix']` etc to add additional wrappers as required for manage mode.

2017-10-20 14:53 UTC, andrewbelcher commented on layouts/tab_content_stacked/contacts-tab-content-stacked.html.twig
> +  <div {{ region_attributes.addClass('dash-top') }}>
Apply the classes directly rather than via `region_attributes`.

2017-10-20 15:30 UTC, merged